exports.TIPO_EMAIL_RECUPERACAO_SENHA = "RECUPERACAO DE SENHA";
exports.TIPO_EMAIL_CONFIRMACAO_CADASTRO = "CONFIRMACAO CADASTRO";
exports.TIPO_EMAIL_CONFIRMACAO_ENVIO_OFERTA = "CONFIRMACAO ENVIO OFERTA";
exports.TIPO_EMAIL_RECEBIMENTO_OFERTA = "RECEBIMENTO OFERTA";
exports.TIPO_EMAIL_APROVACAO_OFERTA_USUARIO = "APROVACAO OFERTA USUARIO";
exports.TIPO_EMAIL_REJEICAO_OFERTA_USUARIO = "REJEICAO OFERTA USUARIO";

exports.ASSUNTO_EMAIL_RECUPERACAO_SENHA = "Fale o preco - Recuperação de senha";
exports.ASSUNTO_EMAIL_CONFIRMACAO_CADASTRO = "Fale o preco - Confirmação de cadastro";
exports.ASSUNTO_EMAIL_CONFIRMACAO_ENVIO_OFERTA = "Fale o preco - Sua proposta foi enviada";
exports.ASSUNTO_EMAIL_RECEBIMENTO_OFERTA = "Fale o preco - Você recebeu uma nova oferta";
exports.ASSUNTO_EMAIL_APROVACAO_OFERTA_USUARIO = "Fale o preco - Sua oferta foi aprovada";
exports.ASSUNTO_EMAIL_REJEICAO_OFERTA_USUARIO = "Fale o preco - Sua oferta foi rejeitada";